name: Report Annotate
description: Annotate PR from report e.g. junit
author: Grano Digital

branding:
  icon: flag
  color: yellow

inputs:
  reports:
    description: |-
      Reports to annotate: "<format>|<glob1>[, glob2...]"
      For example: "junit-eslint|junit/lint.xml"
      Default: ["junit|junit/*.xml"]
  ignore:
    description: |-
      Ignore files from report search: "[glob1, glob2...]"
      Default: ['node_modules', 'dist']
  maxAnnotations:
    description: |-
      Maximum number of annotations to create
      Default: 50
  customMatchers:
    description: |-
      Custom matchers to use for parsing reports in JSON format: { "matcher-name": ReportMatcher }
      See ./src/matchers for examples

outputs:
  errors:
    description: Errors found in reports
  warnings:
    description: Warnings found in reports
  notices:
    description: Notices found in reports
  total:
    description: Total annotations created (limited by maxAnnotations)

runs:
  using: node20
  main: dist/index.js
