name: Report Annotate
description: Annotate PR from report e.g. junit
author: Grano Digital

branding:
  icon: flag
  color: yellow

inputs:
  reports:
    description: |-
      Reports to annotate: "format|glob1, glob2, ..."
      For example: "junit-eslint|junit/lint.xml"
    default: |
      junit|junit/*.xml
  ignore:
    description: |-
      Ignore files from report search: "[glob1, glob2...]"
    default: |
      node_modules/**
      dist/**
  max-annotations:
    description: |-
      Maximum number of annotations per type (error/warning/notice)
    default: '10'
  custom-matchers:
    description: |-
      Custom matchers to use for parsing reports in JSON format: { "matcher-name": ReportMatcher }
      See ./src/matchers for examples
  token:
    description: GitHub token for creating PR comments
    default: ${{ github.token }}

outputs:
  errors:
    description: Errors found in reports
  warnings:
    description: Warnings found in reports
  notices:
    description: Notices found in reports
  total:
    description: Total annotations created

runs:
  using: node24
  main: dist/index.js
